package com.madaef.recondoc.entity.dossier

enum class DossierType { BC, CONTRACTUEL }

enum class StatutDossier { BROUILLON, EN_VERIFICATION, VALIDE, REJETE }

enum class TypeDocument {
    FACTURE, BON_COMMANDE, CONTRAT_AVENANT, ORDRE_PAIEMENT,
    CHECKLIST_AUTOCONTROLE, CHECKLIST_PIECES, TABLEAU_CONTROLE,
    PV_RECEPTION, ATTESTATION_FISCALE, FORMULAIRE_FOURNISSEUR,
    MARCHE, BON_COMMANDE_CADRE, CONTRAT_CADRE,
    INCONNU
}

enum class StatutExtraction { EN_ATTENTE, EN_COURS, EXTRAIT, ERREUR, REVUE_HUMAINE_REQUISE }

enum class TypeRetenue { TVA_SOURCE, IS_HONORAIRES, GARANTIE, AUTRE }

enum class StatutCheck { CONFORME, NON_CONFORME, AVERTISSEMENT, NON_APPLICABLE }

enum class Periodicite { MENSUEL, TRIMESTRIEL, ANNUEL, JOURNALIER }
