export interface ValidationRule {
  code: string
  label: string
  desc: string
  category: 'system' | 'checklist'
  appliesToBC: boolean
  appliesToContractuel: boolean
}

export const ALL_RULES: ValidationRule[] = [
  // System rules (generated by ValidationEngine)
  { code: 'R20', label: 'Completude du dossier', desc: 'Verifie que toutes les pieces obligatoires sont presentes', category: 'system', appliesToBC: true, appliesToContractuel: true },
  { code: 'R01', label: 'Concordance montant TTC', desc: 'Compare le TTC de la facture avec le BC', category: 'system', appliesToBC: true, appliesToContractuel: false },
  { code: 'R02', label: 'Concordance montant HT', desc: 'Compare le HT de la facture avec le BC', category: 'system', appliesToBC: true, appliesToContractuel: false },
  { code: 'R03', label: 'Concordance TVA', desc: 'Compare la TVA de la facture avec le BC', category: 'system', appliesToBC: true, appliesToContractuel: false },
  { code: 'R04', label: 'Montant OP = TTC (sans retenues)', desc: 'Verifie que le montant de l\'OP correspond au TTC de la facture', category: 'system', appliesToBC: true, appliesToContractuel: true },
  { code: 'R05', label: 'Montant OP = TTC - retenues', desc: 'Verifie le montant OP apres deduction des retenues a la source', category: 'system', appliesToBC: true, appliesToContractuel: true },
  { code: 'R07', label: 'Reference facture dans l\'OP', desc: 'Verifie que le numero de facture est cite dans l\'ordre de paiement', category: 'system', appliesToBC: true, appliesToContractuel: true },
  { code: 'R08', label: 'Reference BC/contrat dans l\'OP', desc: 'Verifie que le numero de BC ou contrat est cite dans l\'OP', category: 'system', appliesToBC: true, appliesToContractuel: true },
  { code: 'R09', label: 'Coherence ICE', desc: 'Verifie que l\'ICE du fournisseur est identique entre facture et attestation fiscale', category: 'system', appliesToBC: true, appliesToContractuel: true },
  { code: 'R10', label: 'Coherence IF', desc: 'Verifie que l\'identifiant fiscal est identique entre documents', category: 'system', appliesToBC: true, appliesToContractuel: true },
  { code: 'R11', label: 'Coherence RIB', desc: 'Verifie que le RIB de la facture correspond a celui de l\'OP', category: 'system', appliesToBC: true, appliesToContractuel: true },
  { code: 'R12', label: 'Checklist autocontrole', desc: 'Verifie que tous les points de la checklist sont valides', category: 'system', appliesToBC: true, appliesToContractuel: true },
  { code: 'R13', label: 'Tableau de controle', desc: 'Verifie que tous les points du TC sont Conforme ou NA', category: 'system', appliesToBC: true, appliesToContractuel: true },
  { code: 'R14', label: 'Coherence fournisseur', desc: 'Verifie que le nom du fournisseur est coherent entre tous les documents', category: 'system', appliesToBC: true, appliesToContractuel: true },
  { code: 'R15', label: 'Grille tarifaire x duree', desc: 'Verifie que la somme des prix mensuels de l\'avenant x nombre de mois = HT facture', category: 'system', appliesToBC: false, appliesToContractuel: true },
  { code: 'R16', label: 'Verification arithmetique HT+TVA=TTC', desc: 'Verifie que HT + TVA = TTC sur la facture', category: 'system', appliesToBC: true, appliesToContractuel: true },
  { code: 'R17', label: 'Chronologie des dates', desc: 'Verifie que date BC/contrat <= date facture <= date OP', category: 'system', appliesToBC: true, appliesToContractuel: true },
  { code: 'R18', label: 'Validite attestation fiscale', desc: 'Verifie que l\'attestation fiscale a moins de 6 mois', category: 'system', appliesToBC: true, appliesToContractuel: true },

  // Checklist points (from autocontrole CCF-EN-04-V02)
  { code: 'CK01', label: 'Concordance facture / BC / livrables', desc: 'Point 1 du TC : concordance entre la facture, les modalites contractuelles et les livrables', category: 'checklist', appliesToBC: true, appliesToContractuel: true },
  { code: 'CK02', label: 'Verification arithmetique', desc: 'Point 2 du TC : verification arithmetique des montants de la facture', category: 'checklist', appliesToBC: true, appliesToContractuel: true },
  { code: 'CK03', label: 'Delai d\'execution', desc: 'Point 3 du TC : respect du delai d\'execution des prestations', category: 'checklist', appliesToBC: true, appliesToContractuel: true },
  { code: 'CK04', label: 'Avenants et variations', desc: 'Point 4 du TC : respect des plafonds et variations en cas d\'avenants', category: 'checklist', appliesToBC: false, appliesToContractuel: true },
  { code: 'CK05', label: 'Retenues et penalites', desc: 'Point 5 du TC : application des retenues de garantie et penalites', category: 'checklist', appliesToBC: true, appliesToContractuel: true },
  { code: 'CK06', label: 'Signatures et visas', desc: 'Point 6 du TC : existence des signatures des personnes habilitees', category: 'checklist', appliesToBC: true, appliesToContractuel: true },
  { code: 'CK07', label: 'Conformite reglementaire', desc: 'Point 7 du TC : conformite ICE, IF, RC, CNSS sur la facture', category: 'checklist', appliesToBC: true, appliesToContractuel: true },
  { code: 'CK08', label: 'Conformite RIB', desc: 'Point 8 du TC : conformite du RIB contractuel avec celui de la facture', category: 'checklist', appliesToBC: true, appliesToContractuel: true },
  { code: 'CK09', label: 'BL / PV de reception', desc: 'Point 9 du TC : conformite du bon de livraison ou PV de reception', category: 'checklist', appliesToBC: true, appliesToContractuel: true },
  { code: 'CK10', label: 'Habilitations signataires', desc: 'Point 10 du TC : conformite des habilitations des signataires des receptions', category: 'checklist', appliesToBC: true, appliesToContractuel: true },
]

const STORAGE_KEY = 'recondoc_disabled_rules'

export function getDisabledRules(): Set<string> {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    return raw ? new Set(JSON.parse(raw)) : new Set()
  } catch { return new Set() }
}

export function setDisabledRules(codes: Set<string>) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify([...codes]))
}

export function isRuleEnabled(code: string): boolean {
  return !getDisabledRules().has(code)
}

export function getActiveRules(dossierType: 'BC' | 'CONTRACTUEL'): ValidationRule[] {
  const disabled = getDisabledRules()
  return ALL_RULES.filter(r => {
    if (disabled.has(r.code)) return false
    return dossierType === 'BC' ? r.appliesToBC : r.appliesToContractuel
  })
}
